# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91d0e2f41f3088a0e2db96332e0fa93c65e43f0af2161a1e5710351779d08c80b0cd6f8ed521ac8b68e3d3b344222ded3fd24afe4ebd852114941c61a639f01c

test:
  secret_key_base: 64cd15d26c87af74d2f4096526b143c54c515405f8780927055cb40fe8b6dcbfe377f7c1afa48b68e30a52e4113904e13357189815b213330303a6ec002ad4f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
